apiVersion: apps/v1
kind: Deployment
metadata:
  name: priya-jmp-deploy
  labels:
    app: priya-jmp-deploy-lbl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: priya-jmp-app
  template:
    metadata:
      labels:
        app: priya-jmp-app
    spec:
      containers:
      - name: priya-jmp-container
        image: priyajmp/priya-jmp-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: priya-jmp-np-service
  labels:
    app: priya-jmp-app
spec:
  selector:
    app: priya-jmp-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 30001
    port: 8080
    targetPort: 8080
